using Xunit;

namespace ProductCategorization.EntityFrameworkCore;

[CollectionDefinition(ProductCategorizationTestConsts.CollectionDefinitionName)]
public class ProductCategorizationEntityFrameworkCoreCollection : ICollectionFixture<ProductCategorizationEntityFrameworkCoreFixture>
{

}
