using ProductCategorization.EntityFrameworkCore;
using Xunit;

namespace ProductCategorization.EntityFrameworkCore;

public class ProductCategorizationEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<ProductCategorizationEntityFrameworkCoreFixture>
{

}
